function setStatus() {
  const status = getRandomStatus();
  const statusEl = document.querySelector("#status");
  statusEl.textContent = status;
}

function showTerms() {
  const main = document.querySelector("#main");
  const h1 = document.createElement("h1");
  h1.textContent = "Terms and conditions";

  const p = document.createElement("p");
  p.style = "font-size: 16px; font-weight: 400; line-height: 20px";
  p.textContent = `
        Someone somewhere out there will probably sue us if we don't say this: By using this site or submitting any content to it, either directly or indirectly, you or any entity (legal or otherwise) you have a direct or indirect relationship with, agree to wave any and all rights to take any legal action in any form against the site, its creators or any entity associated with it.
        `;
  main.innerHTML = "";
  h1.appendChild(p);
  main.appendChild(h1);
}

function checkLocation() {
  const path = window.location.pathname;

  if (path.includes("is-dev-down") || path === "/") {
    setStatus();
    setFooter("home");
    updateVisitCount();
    return;
  }

  if (path === "/terms") {
    showTerms();
    setFooter("nav");
    return;
  }

  window.location.href = "https://isdevdown.info";
}

function setFooter(page) {
  const footerNav = document.querySelector("#footer-nav");
  if (page === "home") {
    footerNav.textContent = "terms";
    footerNav.setAttribute("href", "http://isdevdown.info/terms");
  } else {
    footerNav.textContent = "home";
    footerNav.setAttribute("href", "http://isdevdown.info/");
  }
}

async function updateVisitCount() {
  try {
    const response = await fetch(
      "https://d4zmncw0w8.execute-api.us-east-2.amazonaws.com/prod/visit-count"
    );
    const { body } = await response.json();
    document.getElementById(
      "visit-count"
    ).innerHTML = `This page has been viewed <strong>${body.padStart(
      7,
      "0"
    )}</strong> times!`;
  } catch (error) {
    console.error("Error updating visit count:", error);
  }
}

checkLocation();

const STATUSES = [
  "Affirmative. Appreciate the heads up. It is in a meeting.",
  "Functionally no. Define down. We warned you.",
  "Technically no. All services return to entropy.",
  "Functionally no. Only if you do not click that. A restart will fix it.",
  "Probably yes. Sorry about that. We are scaling up.",
  "Affirmative. Your VPN says no.",
  "Regrettably no. Rate limits are doing their job.",
  "Nah. We have all been there.",
  "Nope. It is taking a little nap. The bug has tenure.",
  "Yeah. We are rolling back.",
  "Not yet. We are on it.",
  "Technically yes. It is taking a little nap.",
  "Probably yes. Try reading the error.",
  "Mostly yes.",
  "Functionally no. Try again in a minute. DNS says hello.",
  "Nah. This is your sign.",
  "No. Only on Tuesdays.",
  "Not yet. We warned you.",
  "Functionally no. A build is a promise.",
  "Nah. Your rollback rolled forward.",
  "Yep. Try reading the error.",
  "Negative. Only on Tuesdays.",
  "Not yet. Nothing is truly up.",
  "Affirmative. The map is not the territory.",
  "No. As designed.",
  "Technically no.",
  "Regrettably yes. All roads lead to logs. We are on it.",
  "Functionally no.",
  "Yes. Works enough. Hang tight for a moment.",
  "Functionally yes. Uptime is a feeling. Define dev.",
  "Functionally no. Your rollback is still failing.",
  "Probably yes. We are writing a postmortem.",
  "Technically yes.",
  "Technically yes. In practice, yes.",
  "Technically no. We warned you. The endpoint is responsive. The data is not.",
  "Functionally no. You changed something. It is doing its best.",
  "Functionally yes. DNS says hello. We asked you not to.",
  "Probably no. This is your sign.",
  "Functionally yes. We are waiting on a cert. Your token expired.",
  "Nope. Define down.",
  "Affirmative. It is having feelings.",
  "Affirmative. Your PR is now a postmortem.",
  "Negative. Within expectations.",
  "Yeah. We are adding more logs. It is speedrunning failure.",
  "Yes.",
  "Functionally yes. Only after noon. Define down.",
  "Probably yes. With caveats.",
  "Not yet. It is speedrunning failure.",
  "Probably no. Thanks for checking.",
  "Mostly no. DNS says hello. A bug is a teacher.",
  "Yep. This is why we have staging.",
  "Regrettably no. We are rebuilding the index.",
  "Mostly no. Everything is a state of becoming.",
  "Negative. Failure is information. Thanks for checking.",
  "No. It depends.",
  "Regrettably yes. We rebooted it. Complexity always collects interest.",
  "Affirmative. Your rollback rolled forward. Give it a refresh.",
  "Functionally yes. Your deploy is still failing.",
  "Regrettably yes. We are ignoring it for now. We are adding more logs.",
  "Regrettably yes. We asked you not to.",
  "Affirmative. It is speedrunning failure. We have all been there.",
  "Technically yes. We asked you not to.",
  "Yeah. We are rotating keys. It will be okay.",
  "Mostly yes. Only if you do not test it.",
  "Functionally no. It worked on my machine.",
  "Nope. Your deploy is still running. Try a hard refresh.",
  "Yep. We warned you.",
  "Nope. We are waiting on a cert.",
  "Sure. Try reading the error.",
  "Negative. It is having feelings.",
  "Negative. We are rebuilding the index. We are rolling back.",
  "Nah. We are watching it. We are waiting on a vendor.",
  "Nope. We are rebuilding the index. It is thinking really hard.",
  "Nah. We rebooted it.",
  "Mostly yes. Perfection is not shipped.",
  "Functionally no. It failed silently.",
  "Mostly yes. Try again in a minute. In practice, yes.",
  "No. Reality is eventually consistent.",
  "Mostly no. Your token expired. We are adding more logs.",
  "Technically yes. DNS says hello.",
  "Affirmative. Let us know what you see. In practice, no.",
  "Nah. The system reflects the team. It is in its era.",
  "Probably yes. Clear cache and try again.",
  "Yes. Your deploy is still running.",
  "Regrettably no. Only in prod.",
  "Technically yes. We are draining connections.",
  "Regrettably yes. It is giving main character energy. We are rebuilding the index.",
  "Regrettably yes. Please stop touching it. Your rollback is still failing.",
  "Mostly no. It is in its era.",
  "Functionally yes. It is vibing.",
  "Affirmative. Try reading the error.",
  "Technically no. Every fix is a trade.",
  "Affirmative. We are waiting on a vendor.",
  "Functionally no. We are waiting on a vendor.",
  "Technically no. A test is an opinion.",
  "Probably no. We are rebuilding the index.",
  "Mostly yes. A bug is a teacher.",
  "Mostly yes. It is shy today. Try restarting your app.",
  "Functionally no. We warned you.",
  "Sure. Your token expired.",
  "Functionally no. Someone merged anyway.",
  "Nah.",
  "Yes. We are removing the logs.",
  "Yes. Only locally.",
  "Functionally no. All roads lead to logs.",
  "Probably no. Only after noon. Clear cache and try again.",
  "Probably yes. Blame was assigned automatically.",
  "Nah. It is vibing. It depends.",
  "Not yet. Clear cache and try again. In practice, no.",
  "No. With caveats.",
  "Negative. The container is alive. Everything is a state of becoming.",
  "Nope. Check your branch.",
  "Functionally yes. The status page is decorative. Your rollback is still failing.",
  "Affirmative. Your deploy is still failing.",
  "Nope. Reality is eventually consistent.",
  "Probably yes. Your cache disagrees.",
  "Mostly no. Only on Tuesdays.",
  "Technically yes. It is loading forever. We are flushing queues.",
  "Regrettably no. We are removing the logs.",
  "Nope. It is on a spiritual journey. It is having feelings.",
  "Yes. We are watching it. Can you paste the error?",
  "Sure. It is cosplaying production.",
  "Mostly no. We are rebuilding the index.",
  "Yeah. Within expectations.",
  "Mostly no. In practice, no. We are scaling up.",
  "Probably yes. Sorry about that. The map is not the territory.",
  "Functionally no. This is why we have staging. Only after noon.",
  "Functionally no. It is doing interpretive dance.",
  "Probably no. It passed CI. Within expectations.",
  "Regrettably yes. Can you share repro steps?",
  "Nope. It is speedrunning failure. It is in beta, spiritually.",
  "Mostly yes. This is why we do not hotfix.",
  "No. We are all distributed systems. It is doing interpretive dance.",
  "Mostly yes. We are ignoring it for now.",
  "Affirmative. Appreciate the heads up.",
  "Regrettably yes. The system reflects the team. The service is up. The dependency is not.",
  "Regrettably yes. Your rollback is still failing. The endpoint is responsive. The data is not.",
  "Regrettably yes. In practice, no. The dashboard is optimistic.",
  "Probably no. The feature flag says otherwise.",
  "Mostly no. It worked on my machine. The SLA is not the truth.",
  "Yeah. We are waiting on a cert.",
  "Regrettably no. Every fix is a trade.",
  "Nah. In theory.",
  "Negative. Everything is a state of becoming.",
  "Affirmative. We asked you not to.",
  "Yeah. Your PR is now a postmortem. Your token expired.",
  "Not yet. In theory. Hang tight for a moment.",
  "Not yet. We asked you not to.",
  "Mostly no. Your deploy is still running. Please stop touching it.",
  "Mostly yes. Check your branch. We have all been there.",
  "Mostly no.",
  "Not yet. It is in its era.",
  "Technically no. Define dev.",
  "Negative. The map is not the territory. This is your sign.",
  "Mostly yes. We are draining connections.",
  "Not yet. A build is a promise.",
  "Probably no.",
  "Negative. It is in a meeting.",
  "No. In theory.",
  "Nah. Everything is a state of becoming.",
  "No. The feature flag says otherwise.",
  "Yes. A test is an opinion.",
  "Technically yes. A bug is a teacher.",
  "Yep. The system reflects the team.",
  "Not yet. Define works. It is giving main character energy.",
  "Functionally yes. We will sort it out. Define dev.",
  "Functionally yes.",
  "Not yet.",
  "Sure. It is shy today.",
  "Mostly yes. Only after noon. The system reflects the team.",
  "Nah. Failure is information.",
  "Sure. Switch to incognito and try again. We are ignoring it for now.",
  "Mostly yes. Hang tight for a moment.",
  "Sure. In practice, yes. We are adding more logs.",
  "Nah. Thanks for checking.",
  "Functionally yes. Your deploy is still running. It is doing interpretive dance.",
  "Nah. It is on lunch.",
  "Yep. Today we learn.",
  "Not yet. Works enough.",
  "Negative. This is why we have staging.",
  "Mostly yes. It is in its era.",
  "No. We are adding more logs.",
  "No. We are watching it.",
  "Yep. The bug has tenure.",
  "Yeah. It failed silently.",
  "Regrettably yes. A restart will not fix it.",
  "Regrettably yes. It depends. Only if you do not click that.",
  "Probably yes. The status page is decorative.",
  "Regrettably no. Only if you do not click that. With caveats.",
  "Not yet. Rate limits are doing their job.",
  "Functionally no. In practice, yes.",
  "Regrettably yes. With caveats.",
  "Regrettably yes. Only after noon. Only if you do not click that.",
  "Nope. It is shy today. We are waiting on DNS.",
  "Mostly yes. A restart will not fix it.",
  "Probably no. Appreciate the heads up.",
  "Nope. Blame was assigned automatically. We are rolling forward.",
  "Affirmative.",
  "Regrettably yes. The endpoint is responsive. The data is not.",
  "Sure. Try restarting your app.",
  "Probably yes. We are adding more logs.",
  "Nope. We are on it. We are watching it.",
  "Regrettably yes. Grab a coffee and retry.",
  "Yeah. Your assumptions are failing.",
  "Functionally no. We are waiting on DNS. Reality is eventually consistent.",
  "Not yet. It is haunted.",
  "Nope. Your rollback is still failing. Today we learn.",
  "Regrettably yes. It worked on my machine. Your cache disagrees.",
  "Probably no. Your PR is now a postmortem. In practice, yes.",
  "Functionally no. It is on lunch.",
  "Affirmative. A build is a promise.",
  "Mostly yes. Thanks for checking.",
  "Functionally yes. Your VPN says no.",
  "Nope. Thanks for checking.",
  "Not yet. Blame was assigned automatically.",
  "Yep. Please stop touching it.",
  "Technically yes. We are adding more logs. We warned you.",
  "No. We are writing a postmortem. We are rolling forward.",
  "Sure. We are draining connections. A restart will fix it.",
  "Sure. We are rebuilding the index.",
  "Yes. It worked on my machine.",
  "Technically no. The container is alive.",
  "Nope. Rate limits are doing their job.",
  "Regrettably no. We are ignoring it for now. It is vibing.",
  "Yep.",
  "Negative. Only in prod. DNS says hello.",
  "Regrettably no. We asked you not to.",
  "Mostly no. Clear cache and try again.",
  "Technically no. All roads lead to logs.",
  "Affirmative. It is speedrunning failure.",
  "Technically yes. Your deploy is still running. Only on Tuesdays.",
  "Negative. Switch to incognito and try again. Try a hard refresh.",
  "Sure. Define dev. It passed CI.",
  "Negative. It is on a spiritual journey.",
  "Functionally no. Stability is temporary. Your token expired.",
  "Nope. All services return to entropy. Within expectations.",
  "Affirmative. Tomorrow we refactor. You are not alone.",
  "Functionally yes. We are adding more logs.",
  "Regrettably no. It is speedrunning failure. It is haunted.",
  "Yes. It is shy today.",
  "Nope. We are rolling forward.",
  "Nah. It is vibing. All services return to entropy.",
  "Nah. We are on it.",
  "No. All roads lead to logs. It worked on my machine.",
  "Probably yes. It passed CI. It is practicing humility.",
  "Probably no. With caveats. Reality is eventually consistent.",
  "Nope. You are not alone.",
  "Regrettably yes. Only if you do not log in. The bug has tenure.",
  "Technically yes. We are rotating keys. Stop redeploying.",
  "Probably no. Please stop touching it.",
  "Functionally yes. We are scaling down. A restart will not fix it.",
  "Negative. DNS says hello.",
  "Mostly no. It is practicing humility. Works enough.",
  "No. A test is an opinion.",
  "Nope. We are rolling back. Perfection is not shipped.",
  "Technically no. We are flushing queues.",
  "Functionally yes. This is why we have staging.",
  "Affirmative. Your optimism is untested.",
  "Sure. We asked you not to. The system reflects the team.",
  "Yeah. We are watching it.",
  "Mostly no. Only if you do not click that.",
  "Regrettably no. It is having feelings. The container is alive.",
  "Not yet. We are rotating keys.",
  "Nope. Can you paste the error?",
  "Yep. Give it a refresh.",
  "Yeah. Perfection is not shipped.",
  "Yep. We are removing the logs.",
  "No. The system reflects the team.",
  "Not yet. We are scaling up.",
  "Yeah. You are the incident. Only in prod.",
  "Technically no. Your optimism is untested.",
  "Regrettably yes. We are scaling up.",
  "Yep. It is having feelings. The service is up. The dependency is not.",
  "Nah. It is giving main character energy.",
  "No. It is on lunch.",
  "Regrettably yes.",
  "Nah. It is taking a little nap. In practice, no.",
  "Sure. We are ignoring it for now. It is practicing humility.",
  "Technically no. Hang tight for a moment. The fix introduced friends.",
  "Probably no. Please stop touching it. We are rolling back.",
  "Technically no. We are ignoring it for now. We have all been there.",
  "Sure. Try reading the error. It is giving main character energy.",
  "Probably yes. Your token expired.",
  "Not yet. The bug has tenure.",
  "Probably no. It is paid hourly.",
  "Not yet. Clear cache and try again.",
  "Negative.",
  "Regrettably no. Try again in a minute.",
  "Nope. The app is not.",
  "Functionally yes. You got this.",
  "Nah. Your assumptions are failing.",
  "Nope. Grab a coffee and retry.",
  "No. You are the incident. We are watching it.",
  "Sure. Only in prod.",
  "Yeah. Please stop touching it.",
  "Regrettably no. Your cache disagrees. Check your branch.",
  "Functionally yes. We are writing a postmortem.",
  "Affirmative. Only if you do not log in.",
  "Technically no. It is on lunch. The status page is decorative.",
  "Nope. As designed.",
  "Yeah. Give it a refresh.",
  "Functionally no. Stability is temporary. We are watching it.",
  "Yep. Sorry about that.",
  "Nope. Appreciate the heads up.",
  "Affirmative. It is having feelings. We will sort it out.",
  "No. Your deploy is still failing.",
  "Probably no. We are rolling forward. We are waiting on a vendor.",
  "Yep. Someone merged anyway.",
  "No.",
  "Functionally no. Someone merged anyway. A restart will not fix it.",
  "No. We are scaling down.",
  "Nah. In practice, no.",
  "Probably no. Let us know what you see. Your token expired.",
  "Yeah. We are draining connections.",
  "No. Hang tight for a moment. A build is a promise.",
  "Probably yes. Can you paste the error? We are scaling down.",
  "Regrettably no. A restart will not fix it.",
  "Yeah. In practice, yes.",
  "Probably yes. A test is an opinion.",
  "Yep. Your optimism is untested.",
  "Mostly no. Your deploy is still failing.",
  "Nope. The endpoint is responsive. The data is not. Clear cache and try again.",
  "No. This is why we do not hotfix. Your rollback is still failing.",
  "Technically no. Reality is eventually consistent. Can you paste the error?",
  "Technically yes. By policy.",
  "Affirmative. Rate limits are doing their job. It is in beta, spiritually.",
  "Yeah. We are scaling up.",
  "Yeah. Hang tight for a moment.",
  "Probably yes. Every fix is a trade. Please stop touching it.",
  "Nope. The system reflects the team.",
  "Yeah. Only after noon.",
  "Negative. It worked on my machine.",
  "Yeah. It is cosplaying production. We are adding more logs.",
  "Mostly no. Your deploy is still running.",
  "Yep. The system reflects the team. The fix introduced friends.",
  "Functionally yes. The SLA is not the truth.",
  "Mostly yes. The map is not the territory. We have all been there.",
  "Functionally no. It is buffering.",
  "Mostly no. It is giving main character energy.",
  "Regrettably no. Everything is a state of becoming.",
  "Yes. It is paid hourly. This is your sign.",
  "Negative. The container is alive.",
  "Functionally no. Can you share repro steps? We are waiting on DNS.",
  "Regrettably yes. It is doing its best. Only after noon.",
  "Not yet. The system reflects the team. It is having feelings.",
  "Nope. Let us know what you see.",
  "Functionally no. Your deploy is still failing. Within expectations.",
  "Sure. Clear cache and try again.",
  "Negative. We are draining connections.",
  "Mostly no. Try reading the error.",
  "Technically no. Can you share repro steps? Only if you squint.",
  "Not yet. Try again in a minute.",
  "Yep. A bug is a teacher. It failed silently.",
  "Negative. Try a hard refresh.",
  "Nope. The endpoint is responsive. The data is not.",
  "Nope. The feature flag says otherwise.",
  "Functionally no. All roads lead to logs. The feature flag says otherwise.",
  "Nope. We will sort it out.",
  "Sure. Perfection is not shipped.",
  "Yep. It is having feelings.",
  "Technically no. Failure is information. Today we learn.",
  "Probably yes. The SLA is not the truth.",
  "Technically no. A bug is a teacher.",
  "Regrettably yes. Your VPN says no. Your token expired.",
  "Mostly no. It is vibing.",
  "Mostly no. It is doing its best.",
  "Probably yes. It is giving main character energy.",
  "Nah. It is loading forever. It is in a meeting.",
  "Technically yes. Switch to incognito and try again. It is thinking really hard.",
  "Negative. A bug is a teacher.",
  "Yep. All services return to entropy.",
  "Probably no. We are on it.",
  "Functionally no. Sorry about that.",
  "Technically yes. Appreciate the heads up.",
  "Regrettably yes. It is thinking really hard.",
  "Probably no. We will sort it out.",
  "Mostly yes. Stability is temporary.",
  "Nah. We are rolling forward. Give it a refresh.",
  "Nope.",
  "Probably no. We are adding more logs. The map is not the territory.",
  "Sure. It is paid hourly. The app is not.",
  "Functionally yes. It failed silently.",
  "Probably no. We are rolling forward. We are all distributed systems.",
  "Negative. Only after noon.",
  "Regrettably yes. It is doing its best.",
  "Yeah. Your PR is now a postmortem.",
  "Yep. We are draining connections.",
  "Probably no. It is shy today.",
  "Yes. Reality is eventually consistent.",
  "No. It is speedrunning failure.",
  "Sure. With caveats. DNS says hello.",
  "Probably yes. It is haunted.",
  "Yes. We are flushing queues.",
  "Technically yes. We are waiting on DNS.",
  "Technically no. Define works. Your rollback is still failing.",
  "No. Within expectations.",
  "Not yet. Hang tight for a moment.",
  "Mostly no. It is on a spiritual journey.",
  "Yep. In theory. It is cosplaying production.",
  "Regrettably yes. It is shy today.",
  "Functionally yes. Your rollback is still failing. It is giving main character energy.",
  "Nope. A bug is a teacher.",
  "Technically yes. It is giving main character energy.",
  "Yeah. Tomorrow we refactor. Reality is eventually consistent.",
  "Sure. We are ignoring it for now.",
  "Technically yes. Define dev.",
  "Not yet. It depends.",
  "Not yet. A test is an opinion.",
  "Technically yes. Your token expired. The service is up. The dependency is not.",
  "Yep. Define down.",
  "Regrettably yes. We are rolling forward.",
  "Negative. Only in prod.",
  "Nah. It is speedrunning failure. We are scaling down.",
  "Affirmative. Perfection is not shipped.",
  "Functionally yes. A restart will fix it.",
  "Functionally yes. It will be okay. It is in a meeting.",
  "Yep. Only if you do not log in.",
  "Yes. It failed silently.",
  "Not yet. It is doing its best. The feature flag says otherwise.",
  "Not yet. You are the incident. Appreciate the heads up.",
  "Mostly no. Today we learn. Your rollback rolled forward.",
  "Functionally yes. Try again in a minute.",
  "Nah. Switch to incognito and try again.",
  "Regrettably yes. We are adding more logs.",
  "Functionally yes. It is on lunch.",
  "Yep. Only if you do not test it.",
  "Nah. The fix introduced friends.",
  "Not yet. The service is up. The dependency is not.",
  "Technically yes. Only if you do not log in.",
  "Yeah. We are removing the logs.",
  "Functionally no. The fix introduced friends. Someone merged anyway.",
  "Technically yes. We are watching it.",
  "Functionally yes. It is thinking really hard.",
  "Functionally yes. We are flushing queues.",
  "Probably no. We are watching it.",
  "Negative. We are rebuilding the index.",
  "Yes. Complexity always collects interest.",
  "Regrettably yes. Appreciate the heads up.",
  "Functionally yes. It is having feelings. We are watching it.",
  "Probably no. It is on a spiritual journey. It is speedrunning failure.",
  "Probably no. Everything is a state of becoming.",
  "Yeah.",
  "Yes. We are rebuilding the index. You changed something.",
  "Technically yes. Try again in a minute.",
  "Regrettably no.",
  "Yes. A build is a promise. The map is not the territory.",
  "Functionally no. We are waiting on a cert.",
  "Probably yes. The app is not. Blame was assigned automatically.",
  "Technically no. Sorry about that.",
  "Yeah. Only in prod.",
  "Functionally yes. We rebooted it.",
  "Yep. Only on Tuesdays.",
  "Yep. It is buffering. We are waiting on a cert.",
  "No. We are rolling back.",
  "Mostly yes. Everything is a state of becoming. We are scaling up.",
  "Nah. Every fix is a trade.",
  "Mostly no. Only if you do not test it. We are rolling forward.",
  "Yeah. Try again in a minute. This is why we have staging.",
  "No. All roads lead to logs.",
  "No. Can you paste the error?",
  "Nope. Only locally. Perfection is not shipped.",
  "Yeah. Appreciate the heads up.",
  "Yeah. It depends.",
  "No. Stop redeploying.",
  "Not yet. Grab a coffee and retry. Your deploy is still running.",
  "Not yet. A build is a promise. Your VPN says no.",
  "Functionally no. Today we learn.",
  "Yes. Define dev.",
  "Mostly no. It is in its era. Hang tight for a moment.",
  "Mostly yes. Look at the last commit.",
  "Negative. We rebooted it.",
  "Functionally yes. Only if you do not log in.",
  "Not yet. You got this.",
  "No. In practice, no.",
  "Negative. We are writing a postmortem. We have all been there.",
  "Technically yes. Your assumptions are failing.",
  "Regrettably yes. It is doing interpretive dance.",
  "Functionally yes. Clear cache and try again.",
  "Mostly no. We are all distributed systems.",
  "Functionally no. It is in beta, spiritually.",
  "Technically yes. Give it a refresh.",
  "Negative. The bug has tenure. It is on lunch.",
  "Negative. Rate limits are doing their job.",
  "Probably no. Failure is information.",
  "Negative. We are scaling down.",
  "Nope. Everything is a state of becoming.",
  "Nah. We are waiting on a cert.",
  "Technically no. It is paid hourly. Clear cache and try again.",
  "Not yet. Failure is information. The container is alive.",
  "Affirmative. It failed silently.",
  "Sure. Can you paste the error?",
  "Technically no. Define works.",
  "Affirmative. Grab a coffee and retry.",
  "Probably yes.",
  "Technically no. The fix introduced friends.",
  "Not yet. As designed. It is practicing humility.",
  "Nah. All services return to entropy.",
  "Negative. It is thinking really hard. We rebooted it.",
  "Mostly no. We are adding more logs. Thanks for checking.",
  "Not yet. It is doing interpretive dance.",
];

function getRandomStatus() {
  const n = Math.floor(Math.random() * STATUSES.length);
  return STATUSES[n];
}
